export const STORE_INIT = 'init'
export const LOGIN_INIT = 'login/init'
export const LOGIN_SUCCESS = 'login/update'
export const LOGIN_LOGIN = 'login/login'
export const LOGIN_VCODE = 'login/vcode'
export const LOGIN_CHECK = 'login/check'

export const COMMON_GETAREAS = 'common/getareas'
export const COMMON_SETAREAS = 'common/setareas'
export const COMMON_GET_VTYPES = 'common/getvtypes'
export const COMMON_SET_VTYPES = 'common/setvtypes'
export const COMMON_GET_GTYPES = 'common/getvgypes'

export const ORDER_SET = 'order/set'
export const ORDER_RESET = 'order/reset'
export const ORDER_SUBMIT = 'order/submit'
